# ===============================================
# Redis Configuration - Local Environment
# ===============================================
# 로컬 개발 환경 전용 설정
# 공통 설정은 redis.yml 참조
#
# @author Development Team
# @since 1.0.0
# ===============================================

spring:
  data:
    redis:
      host: localhost
      port: 6379
      # password: (로컬은 비밀번호 없음)

      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms

redisson:
  single-server-config:
    address: "redis://localhost:6379"
    connection-pool-size: 8
    connection-minimum-idle-size: 2
