# ===============================================
# Persistence Redis Adapter Configuration
# ===============================================

# Common Redis Settings
spring:
  data:
    redis:
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 4
          max-wait: 3000ms

---
# ===============================================
# Production Profile
# ===============================================
# SECURITY: REDIS_PASSWORD 환경 변수 설정 필수!
# 빈 패스워드는 프로덕션에서 허용되지 않습니다.
# ===============================================
spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

---
# ===============================================
# Test Profile
# ===============================================
spring:
  config:
    activate:
      on-profile: test

  data:
    redis:
      host: localhost
      port: 6379
      password:
