# ===============================================
# AuthHub Client Configuration
# ===============================================
# External AuthHub service client settings
# JWKS (JSON Web Key Set) endpoint for JWT verification
#
# @since 1.0.0
# ===============================================

authhub:
  client:
    jwks-endpoint: /api/v1/auth/jwks
    timeout:
      connection: 3000  # 3 seconds (milliseconds)
      response: 3000    # 3 seconds (milliseconds)
    retry:
      max-attempts: 3
      wait-duration: 100  # milliseconds
    circuit-breaker:
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10000  # 10 seconds
      sliding-window-size: 10
      minimum-number-of-calls: 5

---
# ===============================================
# Local Environment
# ===============================================
spring:
  config:
    activate:
      on-profile: local

authhub:
  client:
    base-url: http://localhost:9090

---
# ===============================================
# Test Environment
# ===============================================
spring:
  config:
    activate:
      on-profile: test

authhub:
  client:
    base-url: http://localhost:9090

---
# ===============================================
# Production Environment
# ===============================================
spring:
  config:
    activate:
      on-profile: prod

authhub:
  client:
    base-url: https://auth.set-of.com
